on:
  push:
    branches: [ master ] 

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Query dependencies
        run: |
          install.packages('remotes')
        shell: Rscript {0}
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-
      - name: Install macOS system dependencies
        run: |
          brew install libgit2
          brew install imagemagick@6
          brew install pkg-config
          brew install gdal
      - name: Install dependencies
        run: |
          install.packages('usethis')
          install.packages('devtools')
        shell: Rscript {0}
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-build README
          commit_author: Author <actions@github.com> 
