# This is a basic workflow to help you get started with Actions

name: Staging Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Posts to the staging endpoint to trigger a build of the staging site
    steps:
      - name: Post to Netlify
        run: curl -X POST -d {} ${{ secrets.STAGING_ENDPOINT }}
